# Generated by Django 3.2.7 on 2021-10-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoTropical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('pesoPromUnidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grasaPromedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proteinaPromedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carboPromedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminaC', models.BooleanField(default=False)),
                ('vitaminaD', models.BooleanField(default=False)),
                ('hierro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultaAlimentosApp.pais')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultaAlimentosApp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('alimentoSembrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultaAlimentosApp.alimentotropical')),
                ('zonaCultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultaAlimentosApp.zona')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
